/*!
 * \file      Commissioning.h
 *
 * \brief     End device commissioning parameters
 *
 * \copyright Revised BSD License, see section \ref LICENSE.
 *
 * \code
 *                ______                              _
 *               / _____)             _              | |
 *              ( (____  _____ ____ _| |_ _____  ____| |__
 *               \____ \| ___ |    (_   _) ___ |/ ___)  _ \
 *               _____) ) ____| | | || |_| ____( (___| | | |
 *              (______/|_____)_|_|_| \__)_____)\____)_| |_|
 *              (C)2013-2017 Semtech
 *
 * \endcode
 *
 * \author    Miguel Luis ( Semtech )
 *
 * \author    Gregory Cristian ( Semtech )
 */
#ifndef __LORA_COMMISSIONING_H__
#define __LORA_COMMISSIONING_H__

/*!
 * When set to 1 the application uses the Over-the-Air activation procedure
 * When set to 0 the application uses the Personalization activation procedure
 */
#define OVER_THE_AIR_ACTIVATION                     0

/*!
 * Indicates if the end-device is to be connected to a private or public network
 */
#define LORAWAN_PUBLIC_NETWORK                      true

/*!
 * IEEE Organizationally Unique Identifier ( OUI ) (big endian)
 * \remark This is unique to a company or organization
 */
#define IEEE_OUI                                    0x70, 0xB3, 0xD5

/*!
 * Mote device IEEE EUI (big endian)
 *
 * \remark In this application the value is automatically generated by calling
 *         BoardGetUniqueId function
 */
#define LORAWAN_DEVICE_EUI                          { IEEE_OUI, 0x31, 0xC0, 0x00, 0x04, 0x00 }

//70 b3 d5 31 c0 00 04 00

/*!
 * Application IEEE EUI (big endian)
 */
#define LORAWAN_APPLICATION_EUI                     { 0x70, 0xB3, 0xD5, 0x31, 0xC0, 0x00, 0x00, 0x01 }

//70 b3 d5 31 c0 00 00 01

/*!
 * AES encryption/decryption cipher application key
 */
#define LORAWAN_APPLICATION_KEY                     { 0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C }
//#define LORAWAN_APPLICATION_KEY												{0xE0, 0x8C, 0x28, 0xFF, 0xCF, 0x7A, 0x47, 0xFF, 0x7A, 0xB5, 0xEB, 0x00, 0xBD, 0x00, 0x04, 0x00}
/*!
 * Current network ID
 */
#define LORAWAN_NETWORK_ID                          ( uint32_t )0xAA5E1A

/*!
 * Device address on the network (big endian)
 *
 * \remark In this application the value is automatically generated using
 *         a pseudo random generator seeded with a value derived from
 *         BoardUniqueId value if LORAWAN_DEVICE_ADDRESS is set to 0
 */
#define LORAWAN_DEVICE_ADDRESS                      ( uint32_t )0x28AD9400
// 28 ad 94 00

/*!
 * AES encryption/decryption cipher network session key
 */
#define LORAWAN_NWKSKEY                             { 0xE0, 0x8C, 0x28, 0xFF, 0xCF, 0x7A, 0x47, 0xFF, 0x7A, 0xB5, 0xEB, 0x00, 0xBD, 0x00, 0x04, 0x00 }

//e0 8c 28 ff cf 7a 47 ff 7a b5 eb 00 bd 00 04 00

/*!
 * AES encryption/decryption cipher application session key
 */
#define LORAWAN_APPSKEY                             { 0xE0, 0x8C, 0x28, 0xFF, 0xCF, 0x7A, 0x47, 0xFF, 0x7A, 0xB5, 0xEB, 0x00, 0xBD, 0x00, 0x04, 0x00 }

#endif // __LORA_COMMISSIONING_H__
